In [1]:
import pandas as pd
import csv
import dask.dataframe as dd

In [2]:
# Paths
name_vigilio = '../input_bauti/ultima_campaña/BayerCS-2023.csv'

In [42]:
data = dd.read_csv(name_vigilio,sep=';', dtype={'Movil': 'object'})
data.head()

,Id,Movil,Name,Zone,Field,FieldBatch,SeedHybrid,FromDate,FromPositionId,ToDate,...,Min,Latitude,Longitude,Km,TMin,TAvg,TMax,SpeedMin,SpeedAvg,SpeedMax
0,FF8C9DB2-60C1-458F-BC26-000A4DBAFA9B,130581,La Delia / XJ4942N,J,La Delia,XJ4942N,DK72-10RR2,2023-02-26 10:16:51.0000000,3598524560,2023-02-26 10:52:36.0000000,...,16,-34.16535,-60.64449,0.0,18.6,18.6,18.6,0,0,0
1,FF8C9DB2-60C1-458F-BC26-000A4DBAFA9B,130581,La Delia / XJ4942N,J,La Delia,XJ4942N,DK72-10RR2,2023-02-26 10:16:51.0000000,3598524560,2023-02-26 10:52:36.0000000,...,17,-34.16535,-60.64449,0.0,18.6,18.6,18.6,0,0,0
2,FF8C9DB2-60C1-458F-BC26-000A4DBAFA9B,130581,La Delia / XJ4942N,J,La Delia,XJ4942N,DK72-10RR2,2023-02-26 10:16:51.0000000,3598524560,2023-02-26 10:52:36.0000000,...,18,-34.16535,-60.64449,0.0,18.6,18.6,18.6,0,0,0
3,FF8C9DB2-60C1-458F-BC26-000A4DBAFA9B,130581,La Delia / XJ4942N,J,La Delia,XJ4942N,DK72-10RR2,2023-02-26 10:16:51.0000000,3598524560,2023-02-26 10:52:36.0000000,...,19,-34.16535,-60.64449,0.0,18.6,18.6,18.6,0,0,0
4,FF8C9DB2-60C1-458F-BC26-000A4DBAFA9B,130581,La Delia / XJ4942N,J,La Delia,XJ4942N,DK72-10RR2,2023-02-26 10:16:51.0000000,3598524560,2023-02-26 10:52:36.0000000,...,20,-34.16535,-60.64449,0.0,18.6,18.6,18.6,0,0,0

In [41]:
data['Id'].unique().compute()

0        FF8C9DB2-60C1-458F-BC26-000A4DBAFA9B
1        FBE21BC3-F6CC-42F5-9B64-0011D8E41527
2        C8BC9273-1501-470E-BB58-00147686791E
3        2697E71D-51D8-447F-A5AF-00180E41FCA7
4        CE895AC4-8CEE-4285-9FBE-00199CA427D9
                         ...
14688    6273D6A0-AEB1-4070-B086-FFF63CDB0F39
14689    6560E985-485E-441F-9016-FFF72F1A2716
14690    234483B6-C448-41B3-AE99-FFF9B7D2C439
14691    04269E20-29E4-4D9F-82E4-FFFA56602976
14692    488CD368-B8D7-48C9-A1C8-FFFD043FB5BB
Name: Id, Length: 14693, dtype: object